services:
  db:
    image: postgres:latest
    container_name: ce-db
    env_file: "database/.env"
    ports:
      - "5430:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - coco-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: prod
    container_name: ce-be
    env_file: "backend/.env"
    environment:
      - DB_HOST=db
    volumes:
      - ./backend:/app
      - django_static_files:/app/staticfiles
    depends_on:
      - db
    networks:
      - coco-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
      target: prod
    container_name: ce-nginx
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - coco-network
    volumes:
      - django_static_files:/usr/share/nginx/html/static

volumes:
  postgres_data:
  django_static_files:

networks:
  coco-network:
    driver: bridge
