services:
  db:
    image: postgres:latest
    container_name: ce-db
    env_file: "database/.env"
    ports:
      - "5430:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - coco-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: prod
    container_name: ce-be
    env_file: "backend/.env"
    environment:
      - DB_HOST=db
    volumes:
      - ./backend:/app
      - django_static_files:/app/staticfiles
    depends_on:
      - db
    networks:
      - coco-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
      target: prod
    container_name: ce-nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - coco-network
    volumes:
      - django_static_files:/usr/share/nginx/html/static
      - certbot_www:/var/www/certbot/:ro
      - certbot_conf:/etc/nginx/ssl/:ro

  certbot:
    image: certbot/certbot:latest
    container_name: ce-certbot
    volumes:
      - certbot_www:/var/www/certbot/:rw
      - certbot_conf:/etc/letsencrypt/:rw
    networks:
      - coco-network

volumes:
  postgres_data:
  django_static_files:
  certbot_www:
  certbot_conf:

networks:
  coco-network:
    driver: bridge
