# Generated by Django 5.2 on 2025-04-26 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        error_messages={
                            "blank": "Campo richiesto.",
                            "unique": "Indirizzo e-mail già registrato.",
                        },
                        max_length=254,
                        unique=True,
                        verbose_name="E-mail",
                    ),
                ),
                (
                    "email_confirmed_at",
                    models.DateTimeField(null=True, verbose_name="E-mail confirmed at"),
                ),
                (
                    "password_hash",
                    models.CharField(max_length=128, verbose_name="Password"),
                ),
                (
                    "first_name",
                    models.CharField(max_length=128, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=128, verbose_name="Last name"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=128, verbose_name="Trip Code")),
                ("name", models.CharField(max_length=128, verbose_name="Trip Name")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trips",
                        to="expenses.user",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "code")},
            },
        ),
        migrations.CreateModel(
            name="ExpenseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=128, verbose_name="Expense Category"),
                ),
                (
                    "name",
                    models.CharField(max_length=128, verbose_name="Expense Category"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expense_categories",
                        to="expenses.user",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "code")},
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expense_date",
                    models.DateField(null=True, verbose_name="Expense Date"),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Description"),
                ),
                (
                    "forecast_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Forecast Amount"
                    ),
                ),
                (
                    "actual_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Actual Amount"
                    ),
                ),
                (
                    "amortization_start_date",
                    models.DateField(null=True, verbose_name="Amortization Start Date"),
                ),
                (
                    "amortization_end_date",
                    models.DateField(null=True, verbose_name="Amortization End Date"),
                ),
                ("is_expense", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expenses",
                        to="expenses.expensecategory",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expenses",
                        to="expenses.trip",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expenses",
                        to="expenses.user",
                    ),
                ),
            ],
        ),
    ]
