# Generated by Django 5.2 on 2025-04-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0002_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="expensecategory",
            name="for_expense",
            field=models.BooleanField(default=True, verbose_name="For expenses"),
        ),
    ]
