# Generated by Django 5.2 on 2025-04-27 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0003_expensecategory_for_expense"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="trip",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="expenses",
                to="expenses.trip",
            ),
        ),
    ]
