# Generated by Django 5.2.1 on 2025-11-06 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_alter_expense_actual_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('symbol', models.CharField(max_length=10)),
                ('display_name', models.CharField(max_length=10)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('code',), name='unique_currency_code')],
            },
        ),
    ]
