# Generated by Django 5.2.1 on 2025-11-06 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0006_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="currency",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="expenses",
                to="expenses.currency",
            ),
        ),
    ]
