# Generated by Django 5.2.1 on 2025-11-06 23:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0007_expense_currency"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expense",
            name="forecast_amount",
        ),
    ]
