# Generated by Django 5.2.1 on 2025-11-06 23:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0008_remove_expense_forecast_amount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="expense",
            old_name="actual_amount",
            new_name="amount",
        ),
    ]
