# Generated by Django 5.2.1 on 2025-11-06 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_rename_actual_amount_expense_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='display_name',
            field=models.CharField(max_length=255),
        ),
    ]
