# Generated by Django 5.2.1 on 2026-01-03 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0013_recurringexpense"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="recurring_expense",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="expenses",
                to="expenses.recurringexpense",
            ),
        ),
    ]
