# Generated by Django 5.2.1 on 2026-01-03 02:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0014_expense_recurring_expense"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringexpense",
            name="amortization_duration",
            field=models.IntegerField(
                default=1,
                help_text="Duration for amortization calculation",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Amortization Duration",
            ),
        ),
        migrations.AddField(
            model_name="recurringexpense",
            name="amortization_unit",
            field=models.CharField(
                choices=[
                    ("DAY", "Day"),
                    ("WEEK", "Week"),
                    ("MONTH", "Month"),
                    ("YEAR", "Year"),
                ],
                default="DAY",
                help_text="Unit of measure for amortization duration",
                max_length=10,
                verbose_name="Amortization Unit",
            ),
        ),
    ]
