# Generated by Django 5.2.1 on 2026-01-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0015_recurringexpense_amortization_duration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expensecategory",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
