# Generated by Django 5.2.1 on 2026-01-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0016_expensecategory_is_active_trip_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("max_categories", models.PositiveIntegerField(blank=True, null=True)),
                ("max_trips", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Settings",
                "verbose_name_plural": "Settings",
            },
        ),
        migrations.AlterField(
            model_name="expensecategory",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active"),
        ),
        migrations.AlterField(
            model_name="trip",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active"),
        ),
    ]
