# Generated by Django 5.2.1 on 2026-01-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0017_settings_alter_expensecategory_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='singleton',
            field=models.BooleanField(default=True, editable=False, unique=True),
        ),
    ]
