# Generated by Django 5.2.1 on 2026-07-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0018_settings_singleton'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='is_encrypted',
            field=models.BooleanField(default=False),
        ),
    ]
