# Generated by Django 5.2.1 on 2026-07-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0019_usersettings_is_encrypted'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='encrypted_amount',
            field=models.CharField(blank=True, max_length=255, verbose_name='Encrypted Amount'),
        ),
        migrations.AddField(
            model_name='expense',
            name='encrypted_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Encrypted Description'),
        ),
    ]
