# Generated by Django 5.2.1 on 2026-09-26 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0020_expense_encrypted_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='friends_1', to='expenses.user')),
                ('user_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='friends_2', to='expenses.user')),
            ],
        ),
    ]
