# Generated by Django 5.2.1 on 2026-09-26 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0021_friend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('FRIEND_REQUEST_RECEIVED', 'Friend request received'), ('FRIEND_REQUEST_ACCEPTED', 'Friend request accepted'), ('FRIEND_REQUEST_REJECTED', 'Friend request rejected'), ('SHARED_EXPENSE_REQUESTED', 'Shared expense requested'), ('SHARED_EXPENSE_ACCEPTED', 'Shared expense accepted'), ('SHARED_EXPENSE_REJECTED', 'Shared expense rejected'), ('SHARED_EXPENSE_MODIFIED', 'Shared expense modified'), ('SHARED_EXPENSE_DELETED', 'Shared expense deleted')], max_length=50)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expenses.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SharedExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expenses.user')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expenses.currency')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SharedExpenseParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shared_expense', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expenses.sharedexpense')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expenses.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SharedExpenseNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expenses.notification')),
                ('shared_expense_participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expenses.sharedexpenseparticipant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='shared_expense_participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='expenses.sharedexpenseparticipant'),
        ),
    ]
