# Generated by Django 5.2.1 on 2026-09-26 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0023_expense_unique_shared_expense_participant"),
    ]

    operations = [
        migrations.CreateModel(
            name="SharedExpenseModifiedNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount_before", models.DecimalField(decimal_places=2, max_digits=10)),
                ("amount_after", models.DecimalField(decimal_places=2, max_digits=10)),
                ("number_participants_before", models.PositiveIntegerField()),
                ("number_participants_after", models.PositiveIntegerField()),
                ("you_were_added", models.BooleanField(default=False)),
                ("you_were_removed", models.BooleanField(default=False)),
                (
                    "currency_after",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="expenses.currency",
                    ),
                ),
                (
                    "currency_before",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="expenses.currency",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="expenses.user"
                    ),
                ),
                (
                    "notification",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shared_expense_modified",
                        to="expenses.notification",
                    ),
                ),
                (
                    "shared_expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="expenses.sharedexpense",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
