# Generated by Django 5.2.1 on 2026-09-26 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0024_shared_expense_modified_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedExpenseDeletedNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='expenses.currency')),
                ('deleted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expenses.user')),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='shared_expense_deleted', to='expenses.notification')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
