# Generated by Django 5.2.1 on 2026-09-27 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0025_shared_expense_deleted_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128, verbose_name='Payment Method')),
                ('name', models.CharField(max_length=128, verbose_name='Payment Method')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_methods', to='expenses.user')),
            ],
            options={
                'unique_together': {('user', 'code')},
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expenses.paymentmethod'),
        ),
    ]
