# Generated by Django 5.2.1 on 2026-10-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0026_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='amount_favourite_currency',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Amount Favourite Currency'),
        ),
        migrations.AddField(
            model_name='expense',
            name='encrypted_amount_favourite_currency',
            field=models.CharField(blank=True, max_length=255, verbose_name='Encrypted Amount Favourite Currency'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Actual Amount'),
        ),
    ]
