# Generated by Django 5.2.1 on 2026-10-01 21:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0028_widen_expense_amount_favourite_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="default_statistics_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="default_statistics_start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
